Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,18 +38,18 @@ jobs:
           #   runs-on: ubuntu-latest
           #   title: AMD64 Ubuntu 22.04
           #   ubuntu: "22.04"
-          - arch: aarch_64
-            clang-tools: "14"
-            llvm: "14"
-            runs-on: ubuntu-latest
-            title: AMD64 Ubuntu 22.04
-            ubuntu: "22.04"
-          # - arch: arm64v8
-          #   clang-tools: "10"
-          #   llvm: "10"
-          #   runs-on: buildjet-4vcpu-ubuntu-2204-arm
-          #   title: ARM64 Ubuntu 20.04
-          #   ubuntu: "20.04"
+          # - arch: aarch_64
+          #   clang-tools: "14"
+          #   llvm: "14"
+          #   runs-on: ubuntu-latest
+          #   title: AMD64 Ubuntu 22.04
+          #   ubuntu: "22.04"
+          - arch: arm64v8
+            clang-tools: "10"
+            llvm: "10"
+            runs-on: buildjet-4vcpu-ubuntu-2204-arm
+            title: ARM64 Ubuntu 20.04
+            ubuntu: "20.04"
     env:
       ARCH: ${{ matrix.arch }}
       CLANG_TOOLS: ${{ matrix.clang-tools }}
@@ -136,6 +136,10 @@ jobs:
             df -h
             sudo rm -rf /opt/hostedtoolcache/CodeQL || :
             df -h
+      - name: Set Swap Space
+        uses: pierotofy/set-swap-space@master
+        with:
+          swap-size-gb: 16
       - name: Build C++ libraries
         # env:
         #   AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
@@ -157,94 +161,94 @@ jobs:
           name: ubuntu-shared-lib
           path: arrow-shared-libs-linux.tar.gz
 
-  build-cpp-macos:
-    name: Build C++ libraries macOS ${{ matrix.platform.arch }}
-    runs-on: ${{ matrix.platform.runs_on }}
-    strategy:
-      fail-fast: false
-      matrix:
-        platform:
-          - { runs_on: ["macos-latest"], arch: "x86_64"}
-    env:
-      MACOSX_DEPLOYMENT_TARGET: "10.13"
-    steps:
-      - name: Checkout Arrow
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
-          path: arrow
-          ref: testBuild
-          submodules: recursive
+  # build-cpp-macos:
+  #   name: Build C++ libraries macOS ${{ matrix.platform.arch }}
+  #   runs-on: ${{ matrix.platform.runs_on }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - { runs_on: ["macos-latest"], arch: "x86_64"}
+  #   env:
+  #     MACOSX_DEPLOYMENT_TARGET: "10.13"
+  #   steps:
+  #     - name: Checkout Arrow
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 1
+  #         path: arrow
+  #         ref: testBuild
+  #         submodules: recursive
 
-      - name: Set up Python
-        if: |
-          !contains(matrix.platform.runs_on, 'self-hosted')
-        uses: actions/setup-python@v4
-        with:
-          cache: 'pip'
-          python-version: 3.8
-      - name: Install Archery
-        shell: bash
-        run: pip install -e arrow/dev/archery[all]
-      - name: Install dependencies
-        run: |
-          # We want to use llvm@14 to avoid shared z3
-          # dependency. llvm@14 doesn't depend on z3 and llvm depends
-          # on z3. And Homebrew's z3 provides only shared library. It
-          # doesn't provides static z3 because z3's CMake doesn't accept
-          # building both shared and static libraries at once.
-          # See also: Z3_BUILD_LIBZ3_SHARED in
-          # https://github.com/Z3Prover/z3/blob/master/README-CMake.md
-          #
-          # If llvm is installed, Apache Arrow C++ uses llvm rather than
-          # llvm@14 because llvm is newer than llvm@14.
-          brew uninstall llvm || :
-          brew bundle --file=arrow/cpp/Brewfile
-          # We want to link aws-sdk-cpp statically but Homebrew's
-          # aws-sdk-cpp provides only shared library. If we have
-          # Homebrew's aws-sdk-cpp, our build mix Homebrew's
-          # aws-sdk-cpp and bundled aws-sdk-cpp. We uninstall Homebrew's
-          # aws-sdk-cpp to ensure using only bundled aws-sdk-cpp.
-          brew uninstall aws-sdk-cpp
-          # We want to use bundled RE2 for static linking. If
-          # Homebrew's RE2 is installed, its header file may be used.
-          # We uninstall Homebrew's RE2 to ensure using bundled RE2.
-          brew uninstall grpc || : # gRPC depends on RE2
-          brew uninstall grpc@1.54 || : # gRPC 1.54 may be installed too
-          brew uninstall re2
-          # We want to use bundled Protobuf for static linking. If
-          # Homebrew's Protobuf is installed, its library file may be
-          # used on test  We uninstall Homebrew's Protobuf to ensure using
-          # bundled Protobuf.
-          brew uninstall protobuf
-          brew bundle --file=arrow/java/Brewfile
-      - name: Build C++ libraries
-        env:
-          ARROW_USE_CCACHE: "ON"
-        run: |
-          set -e
-          # make brew Java available to CMake
-          if [ "${{ matrix.platform.arch }}" = "aarch_64" ]; then
-            export JAVA_HOME=$(brew --prefix openjdk@11)/libexec/openjdk.jdk/Contents/Home
-          fi
-          arrow/ci/scripts/java_jni_macos_build.sh \
-            $GITHUB_WORKSPACE/arrow \
-            $GITHUB_WORKSPACE/arrow/cpp-build \
-            $GITHUB_WORKSPACE/arrow/java-dist
-      - name: Compress into single artifact to keep directory structure
-        run: tar -cvzf arrow-shared-libs-macos-${{ matrix.platform.arch }}.tar.gz arrow/java-dist/
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: macos-shared-lib-${{ matrix.platform.arch }}
-          path: arrow-shared-libs-macos-${{ matrix.platform.arch }}.tar.gz
+  #     - name: Set up Python
+  #       if: |
+  #         !contains(matrix.platform.runs_on, 'self-hosted')
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         cache: 'pip'
+  #         python-version: 3.8
+  #     - name: Install Archery
+  #       shell: bash
+  #       run: pip install -e arrow/dev/archery[all]
+  #     - name: Install dependencies
+  #       run: |
+  #         # We want to use llvm@14 to avoid shared z3
+  #         # dependency. llvm@14 doesn't depend on z3 and llvm depends
+  #         # on z3. And Homebrew's z3 provides only shared library. It
+  #         # doesn't provides static z3 because z3's CMake doesn't accept
+  #         # building both shared and static libraries at once.
+  #         # See also: Z3_BUILD_LIBZ3_SHARED in
+  #         # https://github.com/Z3Prover/z3/blob/master/README-CMake.md
+  #         #
+  #         # If llvm is installed, Apache Arrow C++ uses llvm rather than
+  #         # llvm@14 because llvm is newer than llvm@14.
+  #         brew uninstall llvm || :
+  #         brew bundle --file=arrow/cpp/Brewfile
+  #         # We want to link aws-sdk-cpp statically but Homebrew's
+  #         # aws-sdk-cpp provides only shared library. If we have
+  #         # Homebrew's aws-sdk-cpp, our build mix Homebrew's
+  #         # aws-sdk-cpp and bundled aws-sdk-cpp. We uninstall Homebrew's
+  #         # aws-sdk-cpp to ensure using only bundled aws-sdk-cpp.
+  #         brew uninstall aws-sdk-cpp
+  #         # We want to use bundled RE2 for static linking. If
+  #         # Homebrew's RE2 is installed, its header file may be used.
+  #         # We uninstall Homebrew's RE2 to ensure using bundled RE2.
+  #         brew uninstall grpc || : # gRPC depends on RE2
+  #         brew uninstall grpc@1.54 || : # gRPC 1.54 may be installed too
+  #         brew uninstall re2
+  #         # We want to use bundled Protobuf for static linking. If
+  #         # Homebrew's Protobuf is installed, its library file may be
+  #         # used on test  We uninstall Homebrew's Protobuf to ensure using
+  #         # bundled Protobuf.
+  #         brew uninstall protobuf
+  #         brew bundle --file=arrow/java/Brewfile
+  #     - name: Build C++ libraries
+  #       env:
+  #         ARROW_USE_CCACHE: "ON"
+  #       run: |
+  #         set -e
+  #         # make brew Java available to CMake
+  #         if [ "${{ matrix.platform.arch }}" = "aarch_64" ]; then
+  #           export JAVA_HOME=$(brew --prefix openjdk@11)/libexec/openjdk.jdk/Contents/Home
+  #         fi
+  #         arrow/ci/scripts/java_jni_macos_build.sh \
+  #           $GITHUB_WORKSPACE/arrow \
+  #           $GITHUB_WORKSPACE/arrow/cpp-build \
+  #           $GITHUB_WORKSPACE/arrow/java-dist
+  #     - name: Compress into single artifact to keep directory structure
+  #       run: tar -cvzf arrow-shared-libs-macos-${{ matrix.platform.arch }}.tar.gz arrow/java-dist/
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: macos-shared-lib-${{ matrix.platform.arch }}
+  #         path: arrow-shared-libs-macos-${{ matrix.platform.arch }}.tar.gz
 
   package-jars:
     name: Build jar files
     runs-on: macos-latest
     needs:
       - build-cpp-ubuntu
-      - build-cpp-macos
+      # - build-cpp-macos
     steps:
       - name: Checkout Arrow
         uses: actions/checkout@v3
